-- Migration: Add check_in_code column to users table
-- Description: Adds a check-in code column for secure guest login. Admin/Supervisor can generate this code when guest checks in.
-- Date: 2025-01-XX

ALTER TABLE users
ADD COLUMN IF NOT EXISTS check_in_code VARCHAR(50);

-- Add index for faster lookups
CREATE INDEX IF NOT EXISTS idx_users_check_in_code ON users (check_in_code);

-- Add comment
COMMENT ON COLUMN users.check_in_code IS 'Secure check-in code for guest login. Generated by Admin/Supervisor during check-in.';

