
import React, { createContext, useState, useContext, useEffect, ReactNode } from 'react';

type Language = 'English' | 'Vietnamese' | 'Korean' | 'Japanese' | 'Chinese' | 'French' | 'Russian';

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

// Dictionary of translations
const TRANSLATIONS: Record<string, Record<string, string>> = {
  English: {
    // General
    'welcome_back': 'Welcome back,',
    'room': 'Room',
    'loading': 'Loading...',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'logout': 'Logout',
    'back': 'Back',
    'save': 'Save',
    'submit': 'Submit',
    
    // PWA Install
    'install_app': 'Install App',
    'install': 'Install',
    'not_now': 'Not Now',
    'install_benefits': 'Get faster access and offline support',
    'install_ios_instructions': 'Add to Home Screen for a better experience',
    'ios_install_hint': 'Tap Share → Add to Home Screen',
    
    // Nav & Home
    'home': 'Home',
    'concierge': 'Concierge',
    'account': 'Account',
    'buggy': 'Buggy',
    'chat_ai': 'Chat AI',
    'exclusive_offers': 'Exclusive Offers',
    'resort_services': 'Resort Services',
    
    // Services
    'dining': 'In-Room Dining',
    'spa': 'Spa & Wellness',
    'pool': 'Pool Services',
    'butler': 'Butler Request',
    'events': 'Resort Events',
    'housekeeping': 'Housekeeping',
    
    // Status
    'PENDING': 'Pending',
    'CONFIRMED': 'Confirmed',
    'COMPLETED': 'Completed',
    'ARRIVING': 'Arriving',
    'ASSIGNED': 'Assigned',
    'ON_TRIP': 'On Trip',
    'SEARCHING': 'Searching',
    'ACTIVE': 'Active',
    
    // Buggy
    'buggy_service': 'Buggy Service',
    'where_to': 'Where to?',
    'search_locations': 'Search locations...',
    'select_dest': 'Select on map or list...',
    'request_buggy': 'Request Buggy',
    'finding_driver': 'Finding driver...',
    'driver_assigned': 'Driver Assigned',
    'driver_arriving': 'Driver Arriving',
    'en_route': 'En Route',
    'arrived': 'Arrived',
    'status_searching': 'Searching for available driver...',
    'status_on_the_way_to': 'On the way to',
    'status_driver_on_the_way': 'on the way',
    'status_driver_arriving': 'arriving',
    'driver_label': 'Driver',
    'status_driver_delayed': 'Driver delayed over 15 min. You can cancel if needed.',
    'status_driver_arriving_wait': 'Driver arriving for over 5 min. Please wait.',
    'shared_ride_total': 'Shared ride ({count} total guests)',
    'cancel_request': 'Cancel Request',
    'cancel_ride': 'Cancel Ride',
    'guest_picked_up': 'Guest Picked Up',
    'estimated': 'Estimated',
    'recent_locations': 'Recent Locations',
    'destination': 'Destination',
    'select_destination': 'Select destination...',
    'pickup_point': 'Pickup Point',
    'number_of_guests': 'Number of Guests',
    'notes_optional': 'Notes (optional)',
    'processing': 'Processing...',
    'detecting_location': 'Detecting location...',
    'location_detecting_desc': 'Using GPS to find your current location...',
    'manual_select_location': 'Select location manually',
    'luggage_special_requests': 'Luggage, special requests...',
    'guest': 'guest',
    'guests': 'guests',
    'pickup_destination_same_error': 'Pickup and destination cannot be the same. Please choose a different location.',
    'failed_to_request_ride': 'Failed to request ride. Please try again.',
    'cannot_cancel_picked_up': 'Cannot cancel ride. Driver has already picked you up.',
    'cannot_cancel_assigned': 'Cannot cancel ride. Driver has already accepted your request.',
    'driver_delayed_cancel': 'Driver has been arriving for over 15 minutes. Are you sure you want to cancel this ride?',
    'waiting_long_cancel': 'You have been waiting for over 10 minutes. Are you sure you want to cancel this ride?',
    'confirm_cancel_ride': 'Are you sure you want to cancel this ride?',
    'ride_cancelled_success': 'Ride cancelled successfully!',
    'failed_to_cancel_ride': 'Failed to cancel ride. Please try again.',
    'popular_locations': 'Popular Locations',
    'no_locations_found': 'No locations found',
    'location_type_villa': 'Villa',
    'location_type_facility': 'Facility',
    'location_type_restaurant': 'Restaurant',
    'select_pickup_location': 'Select Pickup Location',
    'select_destination_location': 'Select Destination',
    
    // Booking
    'shopping_cart': 'Shopping Cart',
    'place_order': 'Request Service',
    'request_received': 'Request Received!',
    'request_confirm_msg': 'We will confirm your request shortly.',
    'add_to_cart': 'Add to Cart',
    'items': 'items',
    
    // Account
    'my_account': 'My Account',
    'reservation_details': 'Reservation Details',
    'villa_type': 'Villa Type',
    'stay_duration': 'Stay Duration',
    'app_language': 'App Language',
    'personal_notes': 'Personal Notes',
    'save_notes': 'Save Notes',
    'experience_feedback': 'Experience Feedback',
    'rate_stay': 'Rate Your Stay',
    'completed_orders': 'Completed Orders',
    'rate_service': 'Rate Service',
    
    // Active Orders
    'active_orders': 'Active Orders',
    'no_active_orders': 'Your cart is empty.',
    'chat_with': 'Chat with',
    'kitchen': 'Kitchen',
    'driver': 'Driver',
    'therapist': 'Therapist',
    'staff': 'Staff',
    
    // Notifications
    'notifications': 'Notifications',
    'no_notifications': 'No notifications.',
    'mark_as_read': 'Mark as read',
    'notification_info': 'INFO',
    'notification_success': 'SUCCESS',
    'notification_warning': 'WARNING',
    
    // Concierge Chat
    'concierge_ai': 'Concierge AI',
    'concierge_welcome': 'Good day! I am your Furama Digital Concierge. How may I assist you today?',
    'get_directions': 'Get Directions',
    'sources': 'Sources',
    'ask_placeholder': 'Ask about dining, spa, or resort info...',
    'live_concierge': 'Live Concierge',
    'listening': 'Listening... Speak naturally.',
    'connecting_voice': 'Connecting to Furama Secure Voice...',
    'end_call': 'End Call',
    'sorry_couldnt_process': "I'm sorry, I couldn't process that.",
    'connection_error': "I apologize, but I'm having trouble connecting right now. Please try again.",
    'beta_feature_title': 'Feature Under Development',
    'beta_feature_message': 'This feature is currently in beta and under development. Please contact us through the following channels:',
    'beta_contact_info': 'Contact Information',
    'beta_contact_phone': 'Phone',
    'beta_contact_email': 'Email',
    'beta_contact_whatsapp': 'WhatsApp',
    'beta_contact_messenger': 'Messenger',
    
    // Filter & Sort
    'filter_all_dietary': 'All Dietary',
    'filter_vegetarian': '🌱 Vegetarian',
    'filter_vegan': '🥬 Vegan',
    'filter_all_prices': 'All Prices',
    'filter_price_under_100k': '< 100,000 VND',
    'filter_price_100k_300k': '100,000 - 300,000 VND',
    'filter_price_300k_500k': '300,000 - 500,000 VND',
    'filter_price_over_500k': '> 500,000 VND',
    'filter_all_duration': 'All Duration',
    'filter_duration_15min': '15 minutes',
    'filter_duration_30min': '30 minutes',
    'filter_duration_1hour': '1 hour',
    'filter_duration_2hours': '2 hours',
    'filter_duration_4hours': '4 hours',
    'sort_name_az': 'Name A-Z',
    'sort_price_low_high': 'Price: Low to High',
    'sort_price_high_low': 'Price: High to Low',
    
    // Error Messages - Microphone
    'error_mic_permission_denied': 'Microphone permission denied. Please allow microphone access in your browser settings.',
    'error_mic_not_found': 'No microphone found. Please connect a microphone and try again.',
    'error_mic_in_use': 'Microphone is already in use by another application. Please close other applications and try again.',
    'error_mic_constraints': 'Microphone constraints could not be satisfied. Please check your microphone settings.',
    'error_mic_security': 'Microphone access blocked due to security restrictions. Please use HTTPS or localhost.',
    'error_mic_not_supported': 'getUserMedia is not supported in this browser. Please use a modern browser.',
    'error_mic_access_failed': 'Failed to access microphone. Please try again.',
    
    // Error Messages - Speech Recognition
    'error_speech_api_not_supported': 'Web Speech API is not supported in this browser. Please use Chrome, Edge, or Safari (latest version).',
    'error_speech_https_required': 'Web Speech API requires HTTPS connection. Please use HTTPS or localhost.',
    'error_speech_no_speech': 'No speech detected. Please speak clearly into the microphone.',
    'error_speech_audio_capture': 'No microphone found or microphone is not accessible. Please check your microphone settings.',
    'error_speech_not_allowed': 'Microphone permission denied. Please allow microphone access in your browser settings.',
    'error_speech_network': 'Network error occurred. Please check your internet connection and try again.',
    'error_speech_aborted': 'Speech recognition was aborted.',
    'error_speech_service_not_allowed': 'Speech recognition service is not allowed. Please check your browser settings.',
    'error_speech_grammar': 'Speech recognition grammar error.',
    'error_speech_language_not_supported': 'Language is not supported. Please try a different language.',
    'error_speech_unknown': 'Speech recognition error occurred. Please try again.',
    
    // Error Messages - Network & API
    'error_network': 'Network error occurred. Please check your connection and try again.',
    'error_api_auth': 'AI API authentication error. Please check your API key configuration.',
    'error_api_unknown': 'An error occurred. Please try again.',
    
    // Error Messages - General
    'error_unknown': 'An unexpected error occurred. Please try again.',
    'error_user_id_not_found': 'User ID not found. Please log in again.',
    'error_update_profile_failed': 'Failed to update profile. Please try again.',
    'error_update_language_failed': 'Failed to update language. Please check your connection and try again.',
    'error_audio_context_not_supported': 'AudioContext is not supported in this browser.',
  },
  Vietnamese: {
    'welcome_back': 'Chào mừng quay lại,',
    'room': 'Phòng',
    'loading': 'Đang tải...',
    'cancel': 'Hủy',
    'confirm': 'Xác nhận',
    'logout': 'Đăng xuất',
    'back': 'Quay lại',
    'save': 'Lưu',
    'submit': 'Gửi',
    
    // PWA Install
    'install_app': 'Cài đặt Ứng dụng',
    'install': 'Cài đặt',
    'not_now': 'Để sau',
    'install_benefits': 'Truy cập nhanh hơn và hỗ trợ offline',
    'install_ios_instructions': 'Thêm vào Màn hình chính để trải nghiệm tốt hơn',
    'ios_install_hint': 'Nhấn Chia sẻ → Thêm vào Màn hình chính',
    'home': 'Trang chủ',
    'concierge': 'Trợ lý',
    'account': 'Tài khoản',
    'buggy': 'Xe điện',
    'chat_ai': 'Chat AI',
    'exclusive_offers': 'Ưu đãi độc quyền',
    'resort_services': 'Dịch vụ nghỉ dưỡng',
    'dining': 'Ẩm thực tại phòng',
    'spa': 'Spa & Sức khỏe',
    'pool': 'Hồ bơi',
    'butler': 'Quản gia',
    'events': 'Sự kiện',
    'PENDING': 'Chờ xử lý',
    'CONFIRMED': 'Đã xác nhận',
    'COMPLETED': 'Hoàn thành',
    'ARRIVING': 'Đang đến',
    'ASSIGNED': 'Đã phân công',
    'ON_TRIP': 'Đang di chuyển',
    'SEARCHING': 'Đang tìm xe',
    'ACTIVE': 'Hoạt động',
    'buggy_service': 'Đặt xe Buggy',
    'where_to': 'Bạn muốn đi đâu?',
    'search_locations': 'Tìm kiếm địa điểm...',
    'select_dest': 'Chọn trên bản đồ...',
    'request_buggy': 'Đặt xe ngay',
    'finding_driver': 'Đang tìm tài xế...',
    'driver_assigned': 'Tài xế đã nhận',
    'driver_arriving': 'Xe đang đến',
    'en_route': 'Đang đi',
    'arrived': 'Đã đến nơi',
    'status_searching': 'Đang tìm tài xế...',
    'status_on_the_way_to': 'Đang trên đường đến',
    'status_driver_on_the_way': 'đang đi',
    'status_driver_arriving': 'đang đến',
    'driver_label': 'Tài xế',
    'status_driver_delayed': 'Tài xế đến trễ hơn 15 phút. Bạn có thể hủy nếu cần.',
    'status_driver_arriving_wait': 'Tài xế đang đến hơn 5 phút. Vui lòng đợi.',
    'shared_ride_total': 'Chuyến đi chung ({count} khách)',
    'cancel_request': 'Hủy yêu cầu',
    'cancel_ride': 'Hủy chuyến',
    'guest_picked_up': 'Đã đón khách',
    'estimated': 'Ước tính',
    'recent_locations': 'Địa điểm gần đây',
    'destination': 'Điểm đến',
    'select_destination': 'Chọn điểm đến...',
    'pickup_point': 'Điểm đón',
    'number_of_guests': 'Số khách',
    'notes_optional': 'Ghi chú (tùy chọn)',
    'processing': 'Đang xử lý...',
    'detecting_location': 'Đang xác định vị trí...',
    'location_detecting_desc': 'Đang sử dụng GPS để tìm vị trí hiện tại của bạn...',
    'manual_select_location': 'Chọn vị trí thủ công',
    'luggage_special_requests': 'Hành lý, yêu cầu đặc biệt...',
    'guest': 'khách',
    'guests': 'khách',
    'pickup_destination_same_error': 'Điểm đón và điểm đến không thể giống nhau. Vui lòng chọn địa điểm khác.',
    'failed_to_request_ride': 'Không thể đặt xe. Vui lòng thử lại.',
    'cannot_cancel_picked_up': 'Không thể hủy chuyến. Tài xế đã đón bạn.',
    'cannot_cancel_assigned': 'Không thể hủy chuyến. Tài xế đã nhận yêu cầu.',
    'driver_delayed_cancel': 'Tài xế đã đến hơn 15 phút. Bạn có chắc muốn hủy chuyến này?',
    'waiting_long_cancel': 'Bạn đã chờ hơn 10 phút. Bạn có chắc muốn hủy chuyến này?',
    'confirm_cancel_ride': 'Bạn có chắc muốn hủy chuyến này?',
    'ride_cancelled_success': 'Đã hủy chuyến thành công!',
    'failed_to_cancel_ride': 'Không thể hủy chuyến. Vui lòng thử lại.',
    'popular_locations': 'Địa điểm phổ biến',
    'no_locations_found': 'Không tìm thấy địa điểm',
    'location_type_villa': 'Villa',
    'location_type_facility': 'Cơ sở vật chất',
    'location_type_restaurant': 'Nhà hàng',
    'select_pickup_location': 'Chọn điểm đón',
    'select_destination_location': 'Chọn điểm đến',
    'shopping_cart': 'Giỏ hàng',
    'place_order': 'Đặt dịch vụ',
    'request_received': 'Đã nhận yêu cầu!',
    'request_confirm_msg': 'Chúng tôi sẽ xác nhận yêu cầu của bạn sớm.',
    'my_account': 'Tài khoản của tôi',
    'reservation_details': 'Thông tin đặt phòng',
    'villa_type': 'Loại Villa',
    'stay_duration': 'Thời gian lưu trú',
    'app_language': 'Ngôn ngữ ứng dụng',
    'personal_notes': 'Ghi chú cá nhân',
    'save_notes': 'Lưu ghi chú',
    'experience_feedback': 'Đánh giá trải nghiệm',
    'rate_stay': 'Đánh giá kỳ nghỉ',
    'completed_orders': 'Lịch sử dịch vụ',
    'rate_service': 'Đánh giá',
    'active_orders': 'Đơn hàng hiện tại',
    'no_active_orders': 'Giỏ hàng trống.',
    'chat_with': 'Chat với',
    'kitchen': 'Bếp',
    'driver': 'Tài xế',
    'therapist': 'Chuyên viên',
    'staff': 'Nhân viên',
    
    // Notifications
    'notifications': 'Thông báo',
    'no_notifications': 'Không có thông báo.',
    'mark_as_read': 'Đánh dấu đã đọc',
    'notification_info': 'THÔNG TIN',
    'notification_success': 'THÀNH CÔNG',
    'notification_warning': 'CẢNH BÁO',
    
    // Concierge Chat
    'concierge_ai': 'Trợ lý AI',
    'concierge_welcome': 'Xin chào! Tôi là Trợ lý Kỹ thuật số Furama. Tôi có thể giúp gì cho bạn hôm nay?',
    'get_directions': 'Chỉ đường',
    'sources': 'Nguồn',
    'ask_placeholder': 'Hỏi về ẩm thực, spa hoặc thông tin resort...',
    'live_concierge': 'Trợ lý Trực tiếp',
    'listening': 'Đang nghe... Hãy nói tự nhiên.',
    'connecting_voice': 'Đang kết nối với Giọng nói Bảo mật Furama...',
    'end_call': 'Kết thúc cuộc gọi',
    'sorry_couldnt_process': 'Xin lỗi, tôi không thể xử lý điều đó.',
    'connection_error': 'Xin lỗi, nhưng tôi đang gặp sự cố kết nối. Vui lòng thử lại.',
    'beta_feature_title': 'Tính năng đang phát triển',
    'beta_feature_message': 'Tính năng này đang ở giai đoạn beta và đang được phát triển. Vui lòng liên hệ với chúng tôi qua các kênh sau:',
    'beta_contact_info': 'Thông tin liên hệ',
    'beta_contact_phone': 'Điện thoại',
    'beta_contact_email': 'Email',
    'beta_contact_whatsapp': 'WhatsApp',
    'beta_contact_messenger': 'Messenger',
    
    // Filter & Sort
    'filter_all_dietary': 'Tất cả chế độ ăn',
    'filter_vegetarian': '🌱 Chay',
    'filter_vegan': '🥬 Thuần chay',
    'filter_all_prices': 'Tất cả giá',
    'filter_price_under_100k': '< 100.000 VND',
    'filter_price_100k_300k': '100.000 - 300.000 VND',
    'filter_price_300k_500k': '300.000 - 500.000 VND',
    'filter_price_over_500k': '> 500.000 VND',
    'filter_all_duration': 'Tất cả thời lượng',
    'filter_duration_15min': '15 phút',
    'filter_duration_30min': '30 phút',
    'filter_duration_1hour': '1 giờ',
    'filter_duration_2hours': '2 giờ',
    'filter_duration_4hours': '4 giờ',
    'sort_name_az': 'Tên A-Z',
    'sort_price_low_high': 'Giá: Thấp đến Cao',
    'sort_price_high_low': 'Giá: Cao đến Thấp',
    
    // Error Messages - Microphone
    'error_mic_permission_denied': 'Quyền truy cập microphone bị từ chối. Vui lòng cho phép truy cập microphone trong cài đặt trình duyệt.',
    'error_mic_not_found': 'Không tìm thấy microphone. Vui lòng kết nối microphone và thử lại.',
    'error_mic_in_use': 'Microphone đang được sử dụng bởi ứng dụng khác. Vui lòng đóng các ứng dụng khác và thử lại.',
    'error_mic_constraints': 'Không thể đáp ứng yêu cầu microphone. Vui lòng kiểm tra cài đặt microphone.',
    'error_mic_security': 'Truy cập microphone bị chặn do hạn chế bảo mật. Vui lòng sử dụng HTTPS hoặc localhost.',
    'error_mic_not_supported': 'getUserMedia không được hỗ trợ trong trình duyệt này. Vui lòng sử dụng trình duyệt hiện đại.',
    'error_mic_access_failed': 'Không thể truy cập microphone. Vui lòng thử lại.',
    
    // Error Messages - Speech Recognition
    'error_speech_api_not_supported': 'Web Speech API không được hỗ trợ trong trình duyệt này. Vui lòng sử dụng Chrome, Edge hoặc Safari (phiên bản mới nhất).',
    'error_speech_https_required': 'Web Speech API yêu cầu kết nối HTTPS. Vui lòng sử dụng HTTPS hoặc localhost.',
    'error_speech_no_speech': 'Không phát hiện giọng nói. Vui lòng nói rõ ràng vào microphone.',
    'error_speech_audio_capture': 'Không tìm thấy microphone hoặc microphone không thể truy cập. Vui lòng kiểm tra cài đặt microphone.',
    'error_speech_not_allowed': 'Quyền truy cập microphone bị từ chối. Vui lòng cho phép truy cập microphone trong cài đặt trình duyệt.',
    'error_speech_network': 'Lỗi mạng xảy ra. Vui lòng kiểm tra kết nối internet và thử lại.',
    'error_speech_aborted': 'Nhận dạng giọng nói đã bị hủy.',
    'error_speech_service_not_allowed': 'Dịch vụ nhận dạng giọng nói không được phép. Vui lòng kiểm tra cài đặt trình duyệt.',
    'error_speech_grammar': 'Lỗi ngữ pháp nhận dạng giọng nói.',
    'error_speech_language_not_supported': 'Ngôn ngữ không được hỗ trợ. Vui lòng thử ngôn ngữ khác.',
    'error_speech_unknown': 'Lỗi nhận dạng giọng nói xảy ra. Vui lòng thử lại.',
    
    // Error Messages - Network & API
    'error_network': 'Lỗi mạng xảy ra. Vui lòng kiểm tra kết nối và thử lại.',
    'error_api_auth': 'Lỗi xác thực AI API. Vui lòng kiểm tra cấu hình API key.',
    'error_api_unknown': 'Đã xảy ra lỗi. Vui lòng thử lại.',
    
    // Error Messages - General
    'error_unknown': 'Đã xảy ra lỗi không mong muốn. Vui lòng thử lại.',
    'error_user_id_not_found': 'Không tìm thấy ID người dùng. Vui lòng đăng nhập lại.',
    'error_update_profile_failed': 'Cập nhật hồ sơ thất bại. Vui lòng thử lại.',
    'error_update_language_failed': 'Cập nhật ngôn ngữ thất bại. Vui lòng kiểm tra kết nối và thử lại.',
    'error_audio_context_not_supported': 'AudioContext không được hỗ trợ trong trình duyệt này.',
  },
  Korean: {
    'welcome_back': '환영합니다,',
    'room': '객실',
    'loading': '로딩 중...',
    'cancel': '취소',
    'confirm': '확인',
    'back': '뒤로',
    'save': '저장',
    'submit': '제출',
    'home': '홈',
    'concierge': '컨시어지',
    'account': '계정',
    'buggy': '버기',
    'chat_ai': 'AI 채팅',
    'exclusive_offers': '독점 혜택',
    'resort_services': '리조트 서비스',
    'dining': '룸 다이닝',
    'spa': '스파 & 웰니스',
    'pool': '수영장 서비스',
    'butler': '버틀러 요청',
    'events': '리조트 이벤트',
    'PENDING': '대기 중',
    'CONFIRMED': '확인됨',
    'COMPLETED': '완료됨',
    'ARRIVING': '도착 중',
    'ASSIGNED': '배정됨',
    'ON_TRIP': '이동 중',
    'SEARCHING': '검색 중',
    'ACTIVE': '진행 중',
    'buggy_service': '버기 서비스',
    'where_to': '어디로 가시나요?',
    'search_locations': '위치 검색...',
    'select_dest': '지도에서 선택...',
    'request_buggy': '버기 요청',
    'finding_driver': '기사 찾는 중...',
    'driver_assigned': '기사 배정됨',
    'driver_arriving': '기사 도착 중',
    'en_route': '이동 중',
    'arrived': '도착',
    'cancel_request': '요청 취소',
    'cancel_ride': '탑승 취소',
    'guest_picked_up': '손님 탑승 완료',
    'estimated': '예상',
    'shopping_cart': '장바구니',
    'place_order': '서비스 요청',
    'request_received': '요청 접수됨!',
    'request_confirm_msg': '곧 요청을 확인하겠습니다.',
    'my_account': '내 계정',
    'reservation_details': '예약 세부 정보',
    'villa_type': '빌라 타입',
    'stay_duration': '숙박 기간',
    'app_language': '앱 언어',
    'personal_notes': '개인 메모',
    'save_notes': '메모 저장',
    'experience_feedback': '경험 평가',
    'rate_stay': '숙박 평가',
    'completed_orders': '완료된 주문',
    'rate_service': '서비스 평가',
    'active_orders': '진행 중인 주문',
    'no_active_orders': '장바구니가 비어 있습니다.',
    'chat_with': '채팅하기',
    'kitchen': '주방',
    'driver': '기사',
    'therapist': '테라피스트',
    'staff': '직원',
    
    // Notifications
    'notifications': '알림',
    'no_notifications': '알림이 없습니다.',
    'mark_as_read': '읽음으로 표시',
    'notification_info': '정보',
    'notification_success': '성공',
    'notification_warning': '경고',
    
    // Concierge Chat
    'concierge_ai': '컨시어지 AI',
    'concierge_welcome': '안녕하세요! 저는 푸라마 디지털 컨시어지입니다. 오늘 무엇을 도와드릴까요?',
    'get_directions': '길 찾기',
    'sources': '출처',
    'ask_placeholder': '다이닝, 스파 또는 리조트 정보에 대해 물어보세요...',
    'live_concierge': '라이브 컨시어지',
    'listening': '듣는 중... 자연스럽게 말씀해 주세요.',
    'connecting_voice': '푸라마 보안 음성에 연결 중...',
    'end_call': '통화 종료',
    'sorry_couldnt_process': '죄송합니다. 처리할 수 없습니다.',
    'connection_error': '죄송합니다. 지금 연결에 문제가 있습니다. 다시 시도해 주세요.',
    'beta_feature_title': '개발 중인 기능',
    'beta_feature_message': '이 기능은 현재 베타 단계이며 개발 중입니다. 다음 채널을 통해 문의해 주세요:',
    'beta_contact_info': '연락처 정보',
    'beta_contact_phone': '전화',
    'beta_contact_email': '이메일',
    'beta_contact_whatsapp': 'WhatsApp',
    'beta_contact_messenger': 'Messenger',
    
    // Filter & Sort
    'filter_all_dietary': '모든 식단',
    'filter_vegetarian': '🌱 채식',
    'filter_vegan': '🥬 비건',
    'filter_all_prices': '모든 가격',
    'filter_price_under_100k': '< 100,000원',
    'filter_price_100k_300k': '100,000 - 300,000원',
    'filter_price_300k_500k': '300,000 - 500,000원',
    'filter_price_over_500k': '> 500,000원',
    'filter_all_duration': '모든 시간',
    'filter_duration_15min': '15분',
    'filter_duration_30min': '30분',
    'filter_duration_1hour': '1시간',
    'filter_duration_2hours': '2시간',
    'filter_duration_4hours': '4시간',
    'sort_name_az': '이름 A-Z',
    'sort_price_low_high': '가격: 낮은 순',
    'sort_price_high_low': '가격: 높은 순',
    
    // Error Messages - Microphone
    'error_mic_permission_denied': '마이크 권한이 거부되었습니다. 브라우저 설정에서 마이크 액세스를 허용해 주세요.',
    'error_mic_not_found': '마이크를 찾을 수 없습니다. 마이크를 연결하고 다시 시도해 주세요.',
    'error_mic_in_use': '마이크가 다른 애플리케이션에서 사용 중입니다. 다른 애플리케이션을 닫고 다시 시도해 주세요.',
    'error_mic_constraints': '마이크 제약 조건을 충족할 수 없습니다. 마이크 설정을 확인해 주세요.',
    'error_mic_security': '보안 제한으로 인해 마이크 액세스가 차단되었습니다. HTTPS 또는 localhost를 사용해 주세요.',
    'error_mic_not_supported': '이 브라우저에서 getUserMedia를 지원하지 않습니다. 최신 브라우저를 사용해 주세요.',
    'error_mic_access_failed': '마이크에 액세스하지 못했습니다. 다시 시도해 주세요.',
    
    // Error Messages - Speech Recognition
    'error_speech_api_not_supported': '이 브라우저에서 Web Speech API를 지원하지 않습니다. Chrome, Edge 또는 Safari(최신 버전)를 사용해 주세요.',
    'error_speech_https_required': 'Web Speech API는 HTTPS 연결이 필요합니다. HTTPS 또는 localhost를 사용해 주세요.',
    'error_speech_no_speech': '음성이 감지되지 않았습니다. 마이크에 명확하게 말씀해 주세요.',
    'error_speech_audio_capture': '마이크를 찾을 수 없거나 액세스할 수 없습니다. 마이크 설정을 확인해 주세요.',
    'error_speech_not_allowed': '마이크 권한이 거부되었습니다. 브라우저 설정에서 마이크 액세스를 허용해 주세요.',
    'error_speech_network': '네트워크 오류가 발생했습니다. 인터넷 연결을 확인하고 다시 시도해 주세요.',
    'error_speech_aborted': '음성 인식이 중단되었습니다.',
    'error_speech_service_not_allowed': '음성 인식 서비스가 허용되지 않습니다. 브라우저 설정을 확인해 주세요.',
    'error_speech_grammar': '음성 인식 문법 오류가 발생했습니다.',
    'error_speech_language_not_supported': '언어가 지원되지 않습니다. 다른 언어를 시도해 주세요.',
    'error_speech_unknown': '음성 인식 오류가 발생했습니다. 다시 시도해 주세요.',
    
    // Error Messages - Network & API
    'error_network': '네트워크 오류가 발생했습니다. 연결을 확인하고 다시 시도해 주세요.',
    'error_api_auth': 'AI API 인증 오류가 발생했습니다. API 키 구성을 확인해 주세요.',
    'error_api_unknown': '오류가 발생했습니다. 다시 시도해 주세요.',
    
    // Error Messages - General
    'error_unknown': '예기치 않은 오류가 발생했습니다. 다시 시도해 주세요.',
    'error_user_id_not_found': '사용자 ID를 찾을 수 없습니다. 다시 로그인해 주세요.',
    'error_update_profile_failed': '프로필 업데이트에 실패했습니다. 다시 시도해 주세요.',
    'error_update_language_failed': '언어 업데이트에 실패했습니다. 연결을 확인하고 다시 시도해 주세요.',
    'error_audio_context_not_supported': '이 브라우저에서 AudioContext를 지원하지 않습니다.',
  },
  Japanese: {
    'welcome_back': 'おかえりなさいませ、',
    'room': '部屋番号',
    'loading': '読み込み中...',
    'cancel': 'キャンセル',
    'confirm': '確認',
    'back': '戻る',
    'save': '保存',
    'submit': '送信',
    'home': 'ホーム',
    'concierge': 'コンシェルジュ',
    'account': 'アカウント',
    'buggy': 'バギー',
    'chat_ai': 'AIチャット',
    'exclusive_offers': '限定オファー',
    'resort_services': 'リゾートサービス',
    'dining': 'インルームダイニング',
    'spa': 'スパ＆ウェルネス',
    'pool': 'プールサービス',
    'butler': 'バトラーリクエスト',
    'events': 'リゾートイベント',
    'PENDING': '保留中',
    'CONFIRMED': '確認済み',
    'COMPLETED': '完了',
    'ARRIVING': '到着中',
    'ASSIGNED': '担当者決定',
    'ON_TRIP': '移動中',
    'SEARCHING': '検索中',
    'ACTIVE': '進行中',
    'buggy_service': 'バギー予約',
    'where_to': 'どちらへ行かれますか？',
    'search_locations': '場所を検索...',
    'select_dest': '地図から選択...',
    'request_buggy': 'バギーを呼ぶ',
    'finding_driver': 'ドライバーを探しています...',
    'driver_assigned': 'ドライバーが見つかりました',
    'driver_arriving': 'ドライバーが向かっています',
    'en_route': '目的地へ移動中',
    'arrived': '到着しました',
    'cancel_request': 'リクエストをキャンセル',
    'cancel_ride': '乗車をキャンセル',
    'guest_picked_up': 'お客様乗車済み',
    'estimated': '推定',
    'shopping_cart': 'カート',
    'place_order': '注文する',
    'request_received': 'リクエストを受け付けました！',
    'request_confirm_msg': '間もなく確認いたします。',
    'my_account': 'マイアカウント',
    'reservation_details': '予約詳細',
    'villa_type': 'ヴィラタイプ',
    'stay_duration': '滞在期間',
    'app_language': 'アプリの言語',
    'personal_notes': '個人的なメモ',
    'save_notes': 'メモを保存',
    'experience_feedback': '体験の評価',
    'rate_stay': '滞在を評価する',
    'completed_orders': '注文履歴',
    'rate_service': 'サービスを評価',
    'active_orders': '進行中の注文',
    'no_active_orders': 'カートは空です。',
    'chat_with': 'チャット：',
    'kitchen': 'キッチン',
    'driver': 'ドライバー',
    'therapist': 'セラピスト',
    'staff': 'スタッフ',
    
    // Notifications
    'notifications': '通知',
    'no_notifications': '通知はありません。',
    'mark_as_read': '既読にする',
    'notification_info': '情報',
    'notification_success': '成功',
    'notification_warning': '警告',
    
    // Concierge Chat
    'concierge_ai': 'コンシェルジュ AI',
    'concierge_welcome': 'こんにちは！私はフラマデジタルコンシェルジュです。本日はどのようにお手伝いできますか？',
    'get_directions': '道順を取得',
    'sources': 'ソース',
    'ask_placeholder': 'ダイニング、スパ、またはリゾート情報についてお尋ねください...',
    'live_concierge': 'ライブコンシェルジュ',
    'listening': '聞いています...自然に話してください。',
    'connecting_voice': 'フラマセキュアボイスに接続中...',
    'end_call': '通話終了',
    'sorry_couldnt_process': '申し訳ございませんが、処理できませんでした。',
    'connection_error': '申し訳ございませんが、現在接続に問題が発生しています。もう一度お試しください。',
    'beta_feature_title': '開発中の機能',
    'beta_feature_message': 'この機能は現在ベータ版で開発中です。以下のチャネルからお問い合わせください：',
    'beta_contact_info': '連絡先情報',
    'beta_contact_phone': '電話',
    'beta_contact_email': 'メール',
    'beta_contact_whatsapp': 'WhatsApp',
    'beta_contact_messenger': 'Messenger',
    
    // Filter & Sort
    'filter_all_dietary': 'すべての食事',
    'filter_vegetarian': '🌱 ベジタリアン',
    'filter_vegan': '🥬 ビーガン',
    'filter_all_prices': 'すべての価格',
    'filter_price_under_100k': '< 100,000 VND',
    'filter_price_100k_300k': '100,000 - 300,000 VND',
    'filter_price_300k_500k': '300,000 - 500,000 VND',
    'filter_price_over_500k': '> 500,000 VND',
    'filter_all_duration': 'すべての時間',
    'filter_duration_15min': '15分',
    'filter_duration_30min': '30分',
    'filter_duration_1hour': '1時間',
    'filter_duration_2hours': '2時間',
    'filter_duration_4hours': '4時間',
    'sort_name_az': '名前 A-Z',
    'sort_price_low_high': '価格: 安い順',
    'sort_price_high_low': '価格: 高い順',
    
    // Error Messages - Microphone
    'error_mic_permission_denied': 'マイクの権限が拒否されました。ブラウザの設定でマイクへのアクセスを許可してください。',
    'error_mic_not_found': 'マイクが見つかりません。マイクを接続して再度お試しください。',
    'error_mic_in_use': 'マイクは他のアプリケーションで使用中です。他のアプリケーションを閉じて再度お試しください。',
    'error_mic_constraints': 'マイクの制約を満たせませんでした。マイクの設定を確認してください。',
    'error_mic_security': 'セキュリティ制限によりマイクへのアクセスがブロックされました。HTTPSまたはlocalhostを使用してください。',
    'error_mic_not_supported': 'このブラウザではgetUserMediaがサポートされていません。最新のブラウザをご使用ください。',
    'error_mic_access_failed': 'マイクにアクセスできませんでした。再度お試しください。',
    
    // Error Messages - Speech Recognition
    'error_speech_api_not_supported': 'このブラウザではWeb Speech APIがサポートされていません。Chrome、Edge、またはSafari（最新版）をご使用ください。',
    'error_speech_https_required': 'Web Speech APIにはHTTPS接続が必要です。HTTPSまたはlocalhostを使用してください。',
    'error_speech_no_speech': '音声が検出されませんでした。マイクにはっきりと話してください。',
    'error_speech_audio_capture': 'マイクが見つからないか、アクセスできません。マイクの設定を確認してください。',
    'error_speech_not_allowed': 'マイクの権限が拒否されました。ブラウザの設定でマイクへのアクセスを許可してください。',
    'error_speech_network': 'ネットワークエラーが発生しました。インターネット接続を確認して再度お試しください。',
    'error_speech_aborted': '音声認識が中止されました。',
    'error_speech_service_not_allowed': '音声認識サービスが許可されていません。ブラウザの設定を確認してください。',
    'error_speech_grammar': '音声認識の文法エラーが発生しました。',
    'error_speech_language_not_supported': '言語がサポートされていません。別の言語をお試しください。',
    'error_speech_unknown': '音声認識エラーが発生しました。再度お試しください。',
    
    // Error Messages - Network & API
    'error_network': 'ネットワークエラーが発生しました。接続を確認して再度お試しください。',
    'error_api_auth': 'AI API認証エラーが発生しました。APIキーの設定を確認してください。',
    'error_api_unknown': 'エラーが発生しました。再度お試しください。',
    
    // Error Messages - General
    'error_unknown': '予期しないエラーが発生しました。再度お試しください。',
    'error_user_id_not_found': 'ユーザーIDが見つかりません。再度ログインしてください。',
    'error_update_profile_failed': 'プロフィールの更新に失敗しました。再度お試しください。',
    'error_update_language_failed': '言語の更新に失敗しました。接続を確認して再度お試しください。',
    'error_audio_context_not_supported': 'このブラウザではAudioContextがサポートされていません。',
  },
  Chinese: {
    'welcome_back': '欢迎回来，',
    'room': '房间号',
    'loading': '加载中...',
    'cancel': '取消',
    'confirm': '确认',
    'back': '返回',
    'save': '保存',
    'submit': '提交',
    'home': '主页',
    'concierge': '礼宾服务',
    'account': '账户',
    'buggy': '电瓶车',
    'chat_ai': 'AI 助手',
    'exclusive_offers': '独家优惠',
    'resort_services': '度假村服务',
    'dining': '客房送餐',
    'spa': '水疗与康体',
    'pool': '泳池服务',
    'butler': '管家服务',
    'events': '度假村活动',
    'PENDING': '待处理',
    'CONFIRMED': '已确认',
    'COMPLETED': '已完成',
    'ARRIVING': '即将到达',
    'ASSIGNED': '已派车',
    'ON_TRIP': '行程中',
    'SEARCHING': '正在搜寻',
    'ACTIVE': '进行中',
    'buggy_service': '预订电瓶车',
    'where_to': '您想去哪里？',
    'search_locations': '搜索地点...',
    'select_dest': '在地图上选择...',
    'request_buggy': '呼叫电瓶车',
    'finding_driver': '正在寻找司机...',
    'driver_assigned': '司机已接单',
    'driver_arriving': '司机正在前往',
    'en_route': '前往目的地中',
    'arrived': '已到达',
    'cancel_request': '取消请求',
    'cancel_ride': '取消行程',
    'guest_picked_up': '客人已上车',
    'estimated': '预计',
    'shopping_cart': '购物车',
    'place_order': '提交订单',
    'request_received': '已收到您的请求！',
    'request_confirm_msg': '我们将尽快确认您的请求。',
    'my_account': '我的账户',
    'reservation_details': '预订详情',
    'villa_type': '别墅类型',
    'stay_duration': '入住时间',
    'app_language': '应用语言',
    'personal_notes': '个人备注',
    'save_notes': '保存备注',
    'experience_feedback': '体验反馈',
    'rate_stay': '评价住宿体验',
    'completed_orders': '历史订单',
    'rate_service': '评价服务',
    'active_orders': '当前订单',
    'no_active_orders': '购物车是空的。',
    'chat_with': '联系',
    'kitchen': '厨房',
    'driver': '司机',
    'therapist': '理疗师',
    'staff': '员工',
    
    // Notifications
    'notifications': '通知',
    'no_notifications': '没有通知。',
    'mark_as_read': '标记为已读',
    'notification_info': '信息',
    'notification_success': '成功',
    'notification_warning': '警告',
    
    // Concierge Chat
    'concierge_ai': '礼宾 AI',
    'concierge_welcome': '您好！我是富丽华数字礼宾。今天我能为您做些什么？',
    'get_directions': '获取路线',
    'sources': '来源',
    'ask_placeholder': '询问餐饮、水疗或度假村信息...',
    'live_concierge': '实时礼宾',
    'listening': '正在聆听...请自然说话。',
    'connecting_voice': '正在连接到富丽华安全语音...',
    'end_call': '结束通话',
    'sorry_couldnt_process': '抱歉，我无法处理该请求。',
    'connection_error': '抱歉，我现在连接遇到问题。请稍后再试。',
    'beta_feature_title': '功能开发中',
    'beta_feature_message': '此功能目前处于测试阶段，正在开发中。请通过以下渠道联系我们：',
    'beta_contact_info': '联系信息',
    'beta_contact_phone': '电话',
    'beta_contact_email': '电子邮件',
    'beta_contact_whatsapp': 'WhatsApp',
    'beta_contact_messenger': 'Messenger',
    
    // Filter & Sort
    'filter_all_dietary': '所有饮食',
    'filter_vegetarian': '🌱 素食',
    'filter_vegan': '🥬 纯素',
    'filter_all_prices': '所有价格',
    'filter_price_under_100k': '< 100,000 越南盾',
    'filter_price_100k_300k': '100,000 - 300,000 越南盾',
    'filter_price_300k_500k': '300,000 - 500,000 越南盾',
    'filter_price_over_500k': '> 500,000 越南盾',
    'filter_all_duration': '所有时长',
    'filter_duration_15min': '15分钟',
    'filter_duration_30min': '30分钟',
    'filter_duration_1hour': '1小时',
    'filter_duration_2hours': '2小时',
    'filter_duration_4hours': '4小时',
    'sort_name_az': '名称 A-Z',
    'sort_price_low_high': '价格: 低到高',
    'sort_price_high_low': '价格: 高到低',
    
    // Error Messages - Microphone
    'error_mic_permission_denied': '麦克风权限被拒绝。请在浏览器设置中允许麦克风访问。',
    'error_mic_not_found': '未找到麦克风。请连接麦克风后重试。',
    'error_mic_in_use': '麦克风正被其他应用程序使用。请关闭其他应用程序后重试。',
    'error_mic_constraints': '无法满足麦克风约束条件。请检查麦克风设置。',
    'error_mic_security': '由于安全限制，麦克风访问被阻止。请使用HTTPS或localhost。',
    'error_mic_not_supported': '此浏览器不支持getUserMedia。请使用现代浏览器。',
    'error_mic_access_failed': '无法访问麦克风。请重试。',
    
    // Error Messages - Speech Recognition
    'error_speech_api_not_supported': '此浏览器不支持Web Speech API。请使用Chrome、Edge或Safari（最新版本）。',
    'error_speech_https_required': 'Web Speech API需要HTTPS连接。请使用HTTPS或localhost。',
    'error_speech_no_speech': '未检测到语音。请对着麦克风清晰说话。',
    'error_speech_audio_capture': '未找到麦克风或麦克风无法访问。请检查麦克风设置。',
    'error_speech_not_allowed': '麦克风权限被拒绝。请在浏览器设置中允许麦克风访问。',
    'error_speech_network': '发生网络错误。请检查互联网连接后重试。',
    'error_speech_aborted': '语音识别已中止。',
    'error_speech_service_not_allowed': '不允许语音识别服务。请检查浏览器设置。',
    'error_speech_grammar': '语音识别语法错误。',
    'error_speech_language_not_supported': '不支持该语言。请尝试其他语言。',
    'error_speech_unknown': '发生语音识别错误。请重试。',
    
    // Error Messages - Network & API
    'error_network': '发生网络错误。请检查连接后重试。',
    'error_api_auth': 'AI API身份验证错误。请检查API密钥配置。',
    'error_api_unknown': '发生错误。请重试。',
    
    // Error Messages - General
    'error_unknown': '发生意外错误。请重试。',
    'error_user_id_not_found': '未找到用户ID。请重新登录。',
    'error_update_profile_failed': '更新个人资料失败。请重试。',
    'error_update_language_failed': '更新语言失败。请检查连接后重试。',
    'error_audio_context_not_supported': '此浏览器不支持AudioContext。',
  },
  Russian: {
    'welcome_back': 'С возвращением,',
    'room': 'Номер',
    'loading': 'Загрузка...',
    'cancel': 'Отмена',
    'confirm': 'Подтвердить',
    'back': 'Назад',
    'save': 'Сохранить',
    'submit': 'Отправить',
    'home': 'Главная',
    'concierge': 'Консьерж',
    'account': 'Аккаунт',
    'buggy': 'Багги',
    'chat_ai': 'Чат с AI',
    'exclusive_offers': 'Эксклюзивные предложения',
    'resort_services': 'Услуги курорта',
    'dining': 'Еда в номер',
    'spa': 'Спа и Велнес',
    'pool': 'Бассейн',
    'butler': 'Дворецкий',
    'events': 'События',
    'PENDING': 'В ожидании',
    'CONFIRMED': 'Подтверждено',
    'COMPLETED': 'Завершено',
    'ARRIVING': 'Подъезжает',
    'ASSIGNED': 'Назначено',
    'ON_TRIP': 'В пути',
    'SEARCHING': 'Поиск',
    'ACTIVE': 'Активно',
    'buggy_service': 'Заказ багги',
    'where_to': 'Куда поедем?',
    'search_locations': 'Поиск местоположений...',
    'select_dest': 'Выберите на карте...',
    'request_buggy': 'Заказать багги',
    'finding_driver': 'Поиск водителя...',
    'driver_assigned': 'Водитель назначен',
    'driver_arriving': 'Водитель подъезжает',
    'en_route': 'В пути',
    'arrived': 'Прибыли',
    'cancel_request': 'Отменить запрос',
    'cancel_ride': 'Отменить поездку',
    'guest_picked_up': 'Гость в машине',
    'estimated': 'Примерно',
    'shopping_cart': 'Корзина',
    'place_order': 'Заказать услугу',
    'request_received': 'Запрос получен!',
    'request_confirm_msg': 'Мы скоро подтвердим ваш запрос.',
    'my_account': 'Мой аккаунт',
    'reservation_details': 'Детали бронирования',
    'villa_type': 'Тип виллы',
    'stay_duration': 'Период проживания',
    'app_language': 'Язык приложения',
    'personal_notes': 'Личные заметки',
    'save_notes': 'Сохранить',
    'experience_feedback': 'Отзыв',
    'rate_stay': 'Оценить проживание',
    'completed_orders': 'История заказов',
    'rate_service': 'Оценить услугу',
    'active_orders': 'Активные заказы',
    'no_active_orders': 'Корзина пуста.',
    'chat_with': 'Чат с',
    'kitchen': 'Кухня',
    'driver': 'Водитель',
    'therapist': 'Терапевт',
    'staff': 'Персонал',
    
    // Notifications
    'notifications': 'Уведомления',
    'no_notifications': 'Нет уведомлений.',
    'mark_as_read': 'Отметить как прочитанное',
    'notification_info': 'ИНФО',
    'notification_success': 'УСПЕХ',
    'notification_warning': 'ПРЕДУПРЕЖДЕНИЕ',
    
    // Concierge Chat
    'concierge_ai': 'Консьерж AI',
    'concierge_welcome': 'Добрый день! Я ваш цифровой консьерж Furama. Чем я могу вам помочь сегодня?',
    'get_directions': 'Получить маршрут',
    'sources': 'Источники',
    'ask_placeholder': 'Спросите о ресторанах, спа или информации о курорте...',
    'live_concierge': 'Живой консьерж',
    'listening': 'Слушаю... Говорите естественно.',
    'connecting_voice': 'Подключение к безопасному голосу Furama...',
    'end_call': 'Завершить звонок',
    'sorry_couldnt_process': 'Извините, я не смог это обработать.',
    'connection_error': 'Извините, но у меня сейчас проблемы с подключением. Пожалуйста, попробуйте еще раз.',
    'beta_feature_title': 'Функция в разработке',
    'beta_feature_message': 'Эта функция находится в стадии бета-тестирования и разработки. Пожалуйста, свяжитесь с нами через следующие каналы:',
    'beta_contact_info': 'Контактная информация',
    'beta_contact_phone': 'Телефон',
    'beta_contact_email': 'Электронная почта',
    'beta_contact_whatsapp': 'WhatsApp',
    'beta_contact_messenger': 'Messenger',
    
    // Filter & Sort
    'filter_all_dietary': 'Все диеты',
    'filter_vegetarian': '🌱 Вегетарианское',
    'filter_vegan': '🥬 Веганское',
    'filter_all_prices': 'Все цены',
    'filter_price_under_100k': '< 100,000 донгов',
    'filter_price_100k_300k': '100,000 - 300,000 донгов',
    'filter_price_300k_500k': '300,000 - 500,000 донгов',
    'filter_price_over_500k': '> 500,000 донгов',
    'filter_all_duration': 'Все время',
    'filter_duration_15min': '15 минут',
    'filter_duration_30min': '30 минут',
    'filter_duration_1hour': '1 час',
    'filter_duration_2hours': '2 часа',
    'filter_duration_4hours': '4 часа',
    'sort_name_az': 'Имя A-Z',
    'sort_price_low_high': 'Цена: от низкой к высокой',
    'sort_price_high_low': 'Цена: от высокой к низкой',
    
    // Error Messages - Microphone
    'error_mic_permission_denied': 'Доступ к микрофону запрещен. Пожалуйста, разрешите доступ к микрофону в настройках браузера.',
    'error_mic_not_found': 'Микрофон не найден. Пожалуйста, подключите микрофон и попробуйте снова.',
    'error_mic_in_use': 'Микрофон уже используется другим приложением. Пожалуйста, закройте другие приложения и попробуйте снова.',
    'error_mic_constraints': 'Не удалось выполнить требования к микрофону. Пожалуйста, проверьте настройки микрофона.',
    'error_mic_security': 'Доступ к микрофону заблокирован из-за ограничений безопасности. Пожалуйста, используйте HTTPS или localhost.',
    'error_mic_not_supported': 'getUserMedia не поддерживается в этом браузере. Пожалуйста, используйте современный браузер.',
    'error_mic_access_failed': 'Не удалось получить доступ к микрофону. Пожалуйста, попробуйте снова.',
    
    // Error Messages - Speech Recognition
    'error_speech_api_not_supported': 'Web Speech API не поддерживается в этом браузере. Пожалуйста, используйте Chrome, Edge или Safari (последняя версия).',
    'error_speech_https_required': 'Web Speech API требует HTTPS-соединения. Пожалуйста, используйте HTTPS или localhost.',
    'error_speech_no_speech': 'Речь не обнаружена. Пожалуйста, говорите четко в микрофон.',
    'error_speech_audio_capture': 'Микрофон не найден или недоступен. Пожалуйста, проверьте настройки микрофона.',
    'error_speech_not_allowed': 'Доступ к микрофону запрещен. Пожалуйста, разрешите доступ к микрофону в настройках браузера.',
    'error_speech_network': 'Произошла сетевая ошибка. Пожалуйста, проверьте подключение к интернету и попробуйте снова.',
    'error_speech_aborted': 'Распознавание речи было прервано.',
    'error_speech_service_not_allowed': 'Служба распознавания речи не разрешена. Пожалуйста, проверьте настройки браузера.',
    'error_speech_grammar': 'Ошибка грамматики распознавания речи.',
    'error_speech_language_not_supported': 'Язык не поддерживается. Пожалуйста, попробуйте другой язык.',
    'error_speech_unknown': 'Произошла ошибка распознавания речи. Пожалуйста, попробуйте снова.',
    
    // Error Messages - Network & API
    'error_network': 'Произошла сетевая ошибка. Пожалуйста, проверьте подключение и попробуйте снова.',
    'error_api_auth': 'Ошибка аутентификации AI API. Пожалуйста, проверьте конфигурацию API-ключа.',
    'error_api_unknown': 'Произошла ошибка. Пожалуйста, попробуйте снова.',
    
    // Error Messages - General
    'error_unknown': 'Произошла непредвиденная ошибка. Пожалуйста, попробуйте снова.',
    'error_user_id_not_found': 'ID пользователя не найден. Пожалуйста, войдите снова.',
    'error_update_profile_failed': 'Не удалось обновить профиль. Пожалуйста, попробуйте снова.',
    'error_update_language_failed': 'Не удалось обновить язык. Пожалуйста, проверьте подключение и попробуйте снова.',
    'error_audio_context_not_supported': 'AudioContext не поддерживается в этом браузере.',
  },
  French: {
    'welcome_back': 'Bon retour,',
    'room': 'Chambre',
    'loading': 'Chargement...',
    'cancel': 'Annuler',
    'confirm': 'Confirmer',
    'back': 'Retour',
    'save': 'Enregistrer',
    'submit': 'Soumettre',
    'home': 'Accueil',
    'concierge': 'Conciergerie',
    'account': 'Compte',
    'buggy': 'Buggy',
    'chat_ai': 'Chat IA',
    'exclusive_offers': 'Offres Exclusives',
    'resort_services': 'Services du Resort',
    'dining': 'Service en Chambre',
    'spa': 'Spa & Bien-être',
    'pool': 'Services Piscine',
    'butler': 'Demande de Majordome',
    'events': 'Événements du Resort',
    'housekeeping': 'Service d\'Étages',
    'PENDING': 'En Attente',
    'CONFIRMED': 'Confirmé',
    'COMPLETED': 'Terminé',
    'ARRIVING': 'En Arrivée',
    'ASSIGNED': 'Assigné',
    'ON_TRIP': 'En Route',
    'SEARCHING': 'Recherche',
    'ACTIVE': 'Actif',
    'buggy_service': 'Service Buggy',
    'where_to': 'Où allez-vous ?',
    'search_locations': 'Rechercher des emplacements...',
    'select_dest': 'Sélectionnez sur la carte ou la liste...',
    'request_buggy': 'Demander un Buggy',
    'finding_driver': 'Recherche d\'un conducteur...',
    'driver_assigned': 'Conducteur Assigné',
    'driver_arriving': 'Conducteur en Arrivée',
    'en_route': 'En Route',
    'arrived': 'Arrivé',
    'cancel_request': 'Annuler la Demande',
    'cancel_ride': 'Annuler la Course',
    'guest_picked_up': 'Client Récupéré',
    'estimated': 'Estimé',
    'recent_locations': 'Emplacements Récents',
    'destination': 'Destination',
    'select_destination': 'Sélectionner la destination...',
    'pickup_point': 'Point de Prise en Charge',
    'number_of_guests': 'Nombre d\'Invités',
    'notes_optional': 'Notes (optionnel)',
    'processing': 'Traitement en cours...',
    'detecting_location': 'Détection de l\'emplacement...',
    'luggage_special_requests': 'Bagages, demandes spéciales...',
    'guest': 'invité',
    'guests': 'invités',
    'pickup_destination_same_error': 'Le point de prise en charge et la destination ne peuvent pas être identiques. Veuillez choisir un autre emplacement.',
    'failed_to_request_ride': 'Échec de la demande de course. Veuillez réessayer.',
    'cannot_cancel_picked_up': 'Impossible d\'annuler la course. Le conducteur vous a déjà récupéré.',
    'cannot_cancel_assigned': 'Impossible d\'annuler la course. Le conducteur a déjà accepté votre demande.',
    'driver_delayed_cancel': 'Le conducteur arrive depuis plus de 15 minutes. Êtes-vous sûr de vouloir annuler cette course ?',
    'waiting_long_cancel': 'Vous attendez depuis plus de 10 minutes. Êtes-vous sûr de vouloir annuler cette course ?',
    'confirm_cancel_ride': 'Êtes-vous sûr de vouloir annuler cette course ?',
    'ride_cancelled_success': 'Course annulée avec succès !',
    'failed_to_cancel_ride': 'Échec de l\'annulation de la course. Veuillez réessayer.',
    'popular_locations': 'Emplacements Populaires',
    'no_locations_found': 'Aucun emplacement trouvé',
    'select_pickup_location': 'Sélectionner le Point de Prise en Charge',
    'select_destination_location': 'Sélectionner la Destination',
    'shopping_cart': 'Panier',
    'place_order': 'Demander un Service',
    'request_received': 'Demande Reçue !',
    'request_confirm_msg': 'Nous confirmerons votre demande sous peu.',
    'add_to_cart': 'Ajouter au Panier',
    'items': 'articles',
    'my_account': 'Mon Compte',
    'reservation_details': 'Détails de la Réservation',
    'villa_type': 'Type de Villa',
    'stay_duration': 'Durée du Séjour',
    'app_language': 'Langue de l\'Application',
    'personal_notes': 'Notes Personnelles',
    'save_notes': 'Enregistrer les Notes',
    'experience_feedback': 'Retour d\'Expérience',
    'rate_stay': 'Évaluer Votre Séjour',
    'completed_orders': 'Commandes Terminées',
    'rate_service': 'Évaluer le Service',
    'active_orders': 'Commandes Actives',
    'no_active_orders': 'Votre panier est vide.',
    'chat_with': 'Chat avec',
    'kitchen': 'Cuisine',
    'driver': 'Conducteur',
    'therapist': 'Thérapeute',
    'staff': 'Personnel',
    'notifications': 'Notifications',
    'no_notifications': 'Aucune notification.',
    'mark_as_read': 'Marquer comme lu',
    'notification_info': 'INFO',
    'notification_success': 'SUCCÈS',
    'notification_warning': 'AVERTISSEMENT',
    'concierge_ai': 'Conciergerie IA',
    'concierge_welcome': 'Bonjour ! Je suis votre Concierge Numérique Furama. Comment puis-je vous aider aujourd\'hui ?',
    'get_directions': 'Obtenir l\'Itinéraire',
    'sources': 'Sources',
    'ask_placeholder': 'Demandez des informations sur la restauration, le spa ou le resort...',
    'live_concierge': 'Concierge en Direct',
    'listening': 'Écoute... Parlez naturellement.',
    'connecting_voice': 'Connexion à la Voix Sécurisée Furama...',
    'end_call': 'Terminer l\'Appel',
    'sorry_couldnt_process': 'Je suis désolé, je n\'ai pas pu traiter cela.',
    'connection_error': 'Je m\'excuse, mais j\'ai des difficultés à me connecter en ce moment. Veuillez réessayer.',
    'beta_feature_title': 'Fonctionnalité en développement',
    'beta_feature_message': 'Cette fonctionnalité est actuellement en version bêta et en cours de développement. Veuillez nous contacter via les canaux suivants :',
    'beta_contact_info': 'Informations de contact',
    'beta_contact_phone': 'Téléphone',
    'beta_contact_email': 'E-mail',
    'beta_contact_whatsapp': 'WhatsApp',
    'beta_contact_messenger': 'Messenger',
    
    // Filter & Sort
    'filter_all_dietary': 'Tous les régimes',
    'filter_vegetarian': '🌱 Végétarien',
    'filter_vegan': '🥬 Végétalien',
    'filter_all_prices': 'Tous les prix',
    'filter_price_under_100k': '< 100 000 VND',
    'filter_price_100k_300k': '100 000 - 300 000 VND',
    'filter_price_300k_500k': '300 000 - 500 000 VND',
    'filter_price_over_500k': '> 500 000 VND',
    'filter_all_duration': 'Toutes les durées',
    'filter_duration_15min': '15 minutes',
    'filter_duration_30min': '30 minutes',
    'filter_duration_1hour': '1 heure',
    'filter_duration_2hours': '2 heures',
    'filter_duration_4hours': '4 heures',
    'sort_name_az': 'Nom A-Z',
    'sort_price_low_high': 'Prix: du plus bas au plus élevé',
    'sort_price_high_low': 'Prix: du plus élevé au plus bas',
    
    // Error Messages - Microphone
    'error_mic_permission_denied': 'Permission du microphone refusée. Veuillez autoriser l\'accès au microphone dans les paramètres de votre navigateur.',
    'error_mic_not_found': 'Aucun microphone trouvé. Veuillez connecter un microphone et réessayer.',
    'error_mic_in_use': 'Le microphone est déjà utilisé par une autre application. Veuillez fermer les autres applications et réessayer.',
    'error_mic_constraints': 'Les contraintes du microphone n\'ont pas pu être satisfaites. Veuillez vérifier les paramètres de votre microphone.',
    'error_mic_security': 'L\'accès au microphone est bloqué en raison de restrictions de sécurité. Veuillez utiliser HTTPS ou localhost.',
    'error_mic_not_supported': 'getUserMedia n\'est pas pris en charge dans ce navigateur. Veuillez utiliser un navigateur moderne.',
    'error_mic_access_failed': 'Échec de l\'accès au microphone. Veuillez réessayer.',
    
    // Error Messages - Speech Recognition
    'error_speech_api_not_supported': 'L\'API Web Speech n\'est pas prise en charge dans ce navigateur. Veuillez utiliser Chrome, Edge ou Safari (dernière version).',
    'error_speech_https_required': 'L\'API Web Speech nécessite une connexion HTTPS. Veuillez utiliser HTTPS ou localhost.',
    'error_speech_no_speech': 'Aucune parole détectée. Veuillez parler clairement dans le microphone.',
    'error_speech_audio_capture': 'Aucun microphone trouvé ou microphone inaccessible. Veuillez vérifier les paramètres de votre microphone.',
    'error_speech_not_allowed': 'Permission du microphone refusée. Veuillez autoriser l\'accès au microphone dans les paramètres de votre navigateur.',
    'error_speech_network': 'Une erreur réseau s\'est produite. Veuillez vérifier votre connexion Internet et réessayer.',
    'error_speech_aborted': 'La reconnaissance vocale a été interrompue.',
    'error_speech_service_not_allowed': 'Le service de reconnaissance vocale n\'est pas autorisé. Veuillez vérifier les paramètres de votre navigateur.',
    'error_speech_grammar': 'Erreur de grammaire de reconnaissance vocale.',
    'error_speech_language_not_supported': 'La langue n\'est pas prise en charge. Veuillez essayer une autre langue.',
    'error_speech_unknown': 'Une erreur de reconnaissance vocale s\'est produite. Veuillez réessayer.',
    
    // Error Messages - Network & API
    'error_network': 'Une erreur réseau s\'est produite. Veuillez vérifier votre connexion et réessayer.',
    'error_api_auth': 'Erreur d\'authentification de l\'API IA. Veuillez vérifier la configuration de votre clé API.',
    'error_api_unknown': 'Une erreur s\'est produite. Veuillez réessayer.',
    
    // Error Messages - General
    'error_unknown': 'Une erreur inattendue s\'est produite. Veuillez réessayer.',
    'error_user_id_not_found': 'ID utilisateur introuvable. Veuillez vous reconnecter.',
    'error_update_profile_failed': 'Échec de la mise à jour du profil. Veuillez réessayer.',
    'error_update_language_failed': 'Échec de la mise à jour de la langue. Veuillez vérifier votre connexion et réessayer.',
    'error_audio_context_not_supported': 'AudioContext n\'est pas pris en charge dans ce navigateur.',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('English');

  const t = (key: string): string => {
    // 1. Try target language
    // 2. Try English fallback
    // 3. Return key as fallback
    const langDict = TRANSLATIONS[language];
    const enDict = TRANSLATIONS['English'];
    
    if (langDict && langDict[key]) return langDict[key];
    if (enDict && enDict[key]) return enDict[key];
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
